<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNdMrxoe\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNdMrxoe/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNdMrxoe.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNdMrxoe\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNdMrxoe\App_KernelDevDebugContainer([
    'container.build_hash' => 'NdMrxoe',
    'container.build_id' => '601df3e8',
    'container.build_time' => 1716143162,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNdMrxoe');
