<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVUiiF2x\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVUiiF2x/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVUiiF2x.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVUiiF2x\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVUiiF2x\App_KernelDevDebugContainer([
    'container.build_hash' => 'VUiiF2x',
    'container.build_id' => '4926ae79',
    'container.build_time' => 1716133137,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVUiiF2x');
