<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'product_list' => [[], ['_controller' => 'App\\Controller\\ProductController::index'], [], [['text', '/products']], [], [], []],
    'product_report' => [[], ['_controller' => 'App\\Controller\\ProductController::report'], [], [['text', '/products/report']], [], [], []],
    'App\Controller\ProductController::index' => [[], ['_controller' => 'App\\Controller\\ProductController::index'], [], [['text', '/products']], [], [], []],
    'App\Controller\ProductController::report' => [[], ['_controller' => 'App\\Controller\\ProductController::report'], [], [['text', '/products/report']], [], [], []],
];
